package xlsToJson

// Defined Error constant
const (
	ERR_CODE_EXCEL_NOT_OPEN                                                 = "EXCEL_CANNOT_BE_OPENED"
	ERR_CODE_EXCEL_SHEET_EMPTY                                              = "EXCEL_SHEET_EMPTY"
	ERR_CODE_SHEET_HEADER_ROW_EMPTY                                         = "EXCEL_SHEET_HEADER_ROW_EMPTY"
	ERR_CODE_MAP_RECEIVED_EMPTY                                             = "EMPTY_STRUCT_XSL_MAP_RECEIVED"
	ERR_CODE_NODE_COLUMN_NAME_NOT_PRESENT_IN_MAP                            = "NODE_COLUMN_NAME_NOT_PRESENT_IN_MAP"
	ERR_CODE_HEADER_EMPTY                                                   = "EXCEL_HEADER_EMPTY"
	ERR_CODE_UNABLE_TO_SET_STRUCT_INFO                                      = "UNABLE_TO_SET_STRUCT_INFO"
	ERR_CODE_INCORRECT_NUMBER_OF_ATTRIBUTE_SET                              = "NUMBER_OF_KEYS_IN_STRUCT_AND_SetAttributeMappingMap_MISMATCHED"
	ERR_CODE_CHILDREN_ARRAY_KEY_NOT_SET                                     = "CHILDREN_ARRAY_KEY_NOT_SET_IN_SetKeyToAppendChildrenNodes"
	ERR_CODE_KEYS_COUNT_MISMATCHED_IN_INPUT_SEND_TO_SETATTRIBUTEMAPPINGMAP  = "HEADER_ROW_COLUMN_AND_MAP_KEYS_COUNT_MISMATCHED_IN_INPUT_SEND_TO_SetAttributeMappingMap"
	ERR_CODE_KEYS_MISMATCHED_IN_ATTRIBUTEMAPPINGMAP                         = "KEYS_MISMATCHED_IN_INPUT_SEND_TO_SetAttributeMappingMap"
	ERR_CODE_KEYS_MISMATCHED_IN_STRUCTKEYVALUEMAP                           = "KEYS_MISMATCHED_IN_INPUT_SEND_TO_SetAttributeMappingMap_AND_struct"
	ERR_CODE_INTERFACE_RECEIVED_IS_NOT_STRUCT                               = "INTERFACE_RECEIVED_IS_NOT_STRUCT"
	ERR_CODE_DATE_FORMAT_PARSING_ERROR                                      = "DATE_FORMAT_PARSING_ERROR"
	ERR_CODE_USERDEFINED_FUNCTION_RETURN_VALUE_AND_STRUCT_KEY_TYPE_MISMATCH = "USERDEFINED_FUNCTION_RETURN_VALUE_AND_STRUCT_KEY_TYPE_MISMATCH"
	ERR_CODE_KEY_NOT_PRESENT_IN_STRUCT                                      = "KEY_NOT_PRESENT_IN_EXCEL"
	ERR_CODE_EMPTY_LIST_RECEIVED                                            = "EMPTY_LIST_RECEIVED"
)
